version: '3.8'

services:
  java:
    build: .
    command: /bin/sh -c "while sleep 1000; do :; done"
  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sd
    